config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'page#home'
  get '/photos', to: 'page#photos'
  get '/map', to: 'page#map'
  get '/riders', to: 'riders#index'
  resources :submissions, only: [:new, :create]
  root to: 'page#home'
  get '*unmatched_route', to: 'application#raise_not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rider.rb
class Rider < ApplicationRecord
  def gmap_url
    "http://maps.google.com/maps?q=#{latitude},#{longitude}"
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, format: { with: /[^@]+@[^@]+\.[a-zA-Z]{2,6}/ }, length: { maximum: 30 }
  validates :slogan, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from Exception, with: :not_found
  rescue_from ActionController::RoutingError, with: :not_found

  def raise_not_found
    raise ActionController::RoutingError.new("No route matches #{params[:unmatched_route]}")
  end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end

  def error
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/500", layout: false, status: :error }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @event_date = '2020/04/01'
  end

  def photos
    @photos = Flickr.photos.search(
      tags: 'bikerace,BoulderBikeTour',
      per_page: 40,
      content_type: 1,
      extras: 'url_s,url_l',
      sort: 'date-posted-desc',
      page: params[:page]
    )
  end

  def map
    @google_maps_api_key = 'AIzaSyC_hMH3EQiAQSp6bGpnR36FlS0S5r6yTDk';
    @riders = Rider.all
    @center = @riders[0]
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  def index
    @riders = Rider.order('first_name desc').all
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to new_submission_path, notice: 'Your slogan was successfully added into our database.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render 'new' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:first_name, :last_name, :email, :slogan)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    request.path == test_path ? 'active' : ''
  end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boulder Bike Tour</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield(:head_tags) %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'shared/header' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/page/home.html.erb
<div class="home-banner" style="background-image:url('<%= image_url('banner.jpg') %>');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8">
        <div class="box">
          <h1>Welcome to <strong>Boulder Bike Tour</strong></h1>
          <h5>Let's go through our site and inspect the details!</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="countdown-wrapper">
    <div class="container">
      <h5>Event starts at</h5>
      <input type="hidden" id="event_date" name="event_date" value="<%= @event_date %>"/>
      <div id="timer"></div>
    </div>
  </div>
</div>
<div class="about-section">
  <div class="container">
    <h1>About the event</h1>
    <div class="row">
      <div class="col-lg-6">
        <p class="lead">Once every decade, an exciting, prestigious, and inspiring bike race takes place in Colorado at the foot of the Rocky Mountains. It's the Boulder Bike Tour, and it's coming up in 2020! </p>
        <p>Our race will start on 2020. 04. 01., so lets start to plan your visit. You can check imagery, give us advice about a new slogan, check riders positions on a map and detailed information about them.</p>
        <a href="<%= photos_path %>" class="btn btn-primary btn-lg mt-5">Our Photos</a>
      </div>
      <div class="col-lg-6">
        <img src="<%= image_url('about.jpg') %>" alt="About Image">
      </div>
    </div>
  </div>
</div>

app/views/page/map.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+@google_maps_api_key %>
  <script>
      var map;
      var markers = [];
      var bounds = new google.maps.LatLngBounds();

      document.addEventListener("DOMContentLoaded", function(){
          initMap(<%= @center.latitude %>, <%= @center.longitude %>);
      });

      function initMap(lat, lng) {
          var centerCoords = new google.maps.LatLng(lat, lng);
          var mapOptions = {
              center: centerCoords,
              zoom: 14,
              scrollwheel: false,
          };
          map = new google.maps.Map(document.getElementById('map'), mapOptions);

          <% @riders.each do |rider| %>
          addMarker('<%= rider.first_name %>', '<%= rider.last_name %>', <%= rider.latitude %>, <%= rider.longitude %>);
          map.fitBounds(bounds);
          <% end %>
      }

      function addMarker(firstName, lastName, latitude, longitude) {
          const location = new google.maps.LatLng(latitude, longitude);
          const marker = new google.maps.Marker({
              position: location,
              map: map,
              animation: google.maps.Animation.DROP
          });
          markers.push(marker);
          bounds.extend(location);
          const infoWindow = new google.maps.InfoWindow({});
          marker.addListener('click', function(){
            infoWindow.open(map, marker);
          });
          infoWindow.setContent(firstName + ' ' + lastName);
      }
  </script>
<% end %>

<div id="map"></div>

<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-6">
      <h2 class="mt-5">Check out where the riders are located at the moment</h2>
      <p>You can get more info about the event's riders by clicking on the markers on the map!</p>
    </div>
  </div>
</div>

app/views/page/photos.html.erb
<div class="container">
  <h1 class="mb-5">Our photos</h1>
  <p class="lead">Check out our photos to get inspired to planning visit the bike race in Colorado.</p>
  <% if @photos.present? %>
    <div class="pagination-wrapper">
      <%= will_paginate @photos, :class => 'digg_pagination', :previous_label => '←', :next_label => '→' %>
    </div>
    <div class="photo-list">
      <% @photos.each_with_index do |photo, index| %>
        <img src="<%= photo.attributes['url_s'] %>" style="display:none;" data-index="<%= index %>"/>
        <a data-index="<%= index %>" class="photo" href="<%= photo.attributes['url_l'] %>" data-lightbox="photo-set">
          <div class="lds-ring"><div></div><div></div><div></div><div></div></div>
        </a>
      <% end %>
    </div>
    <div class="pagination-wrapper">
      <%= will_paginate @photos, :class => 'digg_pagination', :previous_label => '←', :next_label => '→' %>
    </div>
  <% end %>
</div>

app/views/riders/index.html.erb
<div class="riders-banner" style="background-image:url(<%= image_url('riders_banner.jpg') %>);">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <h1>Our Riders</h1>
        <p class="lead">Check out detailed informations of our riders!</p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <hr class="mt-5 mb-5"/>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">City of Origin</th>
        <th scope="col">Current Location</th>
      </tr>
      </thead>

      <tbody>
      <% @riders.each.with_index(1) do |rider, index| %>
        <tr>
          <td scope="row"><%= index %></td>
          <td class="first_name">
            <span><%= rider.first_name %></span>
          </td>
          <td class="last_name">
            <span><%= rider.last_name %></span>
          </td>
          <td class="city">
            <span><%= rider.city %>, <%= rider.state %></span>
          </td>
          <td class="location">
            <a class="btn btn-primary btn-sm" target="_blank" href="<%= rider.gmap_url %>">View on Google</a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    Boulder Bike Tour - © Copyright 2019 - created by <a href="mailto:konyatamas01@gmail.com">Tamas Konya</a>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">
    <img src="<%= image_url('bike_logo.png') %>" alt="Bike Logo"/>
    Boulder Bike Tour
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= current_class?(root_path) %>">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item <%= current_class?(photos_path) %>">
        <a class="nav-link" href="<%= photos_path %>">Photos</a>
      </li>
      <li class="nav-item <%= current_class?(map_path) %>">
        <a class="nav-link" href="<%= map_path %>">Map</a>
      </li>
      <li class="nav-item <%= current_class?(riders_path) %>">
        <a class="nav-link" href="<%= riders_path %>">Riders</a>
      </li>
      <li class="nav-item <%= current_class?(new_submission_path) %>">
        <a class="nav-link" href="<%= new_submission_path %>">Contest</a>
      </li>
    </ul>
  </div>
</nav>

app/views/submissions/new.html.erb
<div class="submission-form">
  <div class="container">

    <h1>Your idea</h1>
    <p class="lead">We are sponsoring for anyone to come up with a slogan for the race. Please submit your slogan idea to us</p>

    <%= form_for @submission, url: { action: 'create'}, html: { class: 'form'} do |f| %>

      <% if flash[:notice] %>
        <p class="notice alert alert-primary"><%= notice %></p>
      <% end %>

      <% if f.object.errors.any? %>
        <ul class="form-errors">
          <%=raw f.object.errors.full_messages.join('<br />') %>
        </ul>
      <% end %>

      <div class="row align-items-center">
        <div class="col-md-12 col-lg-6">
          <div class="form-group">
            <label>First Name</label>
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Last Name</label>
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Email Address</label>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Your slogan idea</label>
            <%= f.text_area :slogan, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit "Submit", class:'btn btn-primary btn-lg' %>
          </div>
        </div>
        <div class="d-none col-lg-6 d-lg-block">
          <img src="<%= image_url('idea.png') %>" alt="Idea image" />
        </div>
      </div>
    <% end %>

  </div>
</div>